Repository cloudbees-oss/terraform-aws-cloudbees-ci-eks-addon, pull requests merged in 2024-05, with the labels that each got.

#120 Docs. Typo Missing branches for links
  README.md
Labels: documentation

#121 [Docs] Adding Missing description of Deployed Applications
  blueprints/02-at-scale/README.md
Labels: documentation

#122 [Observability] Implementing Opentelemetry with Grafana Tempo
  CONTRIBUTING.md
  blueprints/01-getting-started/img/getting-started.k8s.drawio.svg
  blueprints/02-at-scale/casc/mc/parent/catalog/catalog.2.440.2.1.yaml
  blueprints/02-at-scale/casc/mc/parent/plugins/plugins.2.440.2.1.minimal.yaml
  blueprints/02-at-scale/k8s/kube-prom-stack-values.yml
  blueprints/02-at-scale/main.tf
Labels: enhancement

#123 [Default values.yaml] Delete PV when deleting Controllers via UI
  values.yml
Labels: enhancement

#127 [Casc API 2.0] Migration from Casc API 1.0 to 2.0
  Makefile
  blueprints/02-at-scale/casc/mc/ha/bundle.yaml
  blueprints/02-at-scale/casc/mc/none-ha/bundle.yaml
  blueprints/02-at-scale/casc/mc/parent/jcasc/security.yaml
  blueprints/02-at-scale/casc/mc/parent/plugins/plugins.2.440.3.7.minimal.yaml
  blueprints/02-at-scale/casc/mc/parent/plugins/plugins.yaml
  blueprints/02-at-scale/casc/oc/jcasc/security.yaml
  blueprints/02-at-scale/casc/oc/plugins/plugins.2.440.3.7.minimal.yaml
  blueprints/02-at-scale/casc/oc/plugins/plugins.yaml
  blueprints/02-at-scale/casc/oc/variables/variables.yaml
  blueprints/02-at-scale/img/at-scale.k8s.drawio.svg
  blueprints/02-at-scale/k8s/secrets-values.yml.example
  blueprints/helpers.sh
Labels: enhancement

#126 [Docs] Expanding details on the upgrade process
  CONTRIBUTING.md
Labels: documentation

#129 [Blueprint 02-At scale] Velero: Validating CloudBees Best Practices
  blueprints/02-at-scale/README.md
  blueprints/02-at-scale/main.tf
  blueprints/02-at-scale/outputs.tf
  blueprints/helpers.sh
Labels: enhancement

#132 [01-getting-started Using] Using AL2023_ARM_64_STANDARD as AMI
  blueprints/01-getting-started/README.md
  blueprints/01-getting-started/img/getting-started.architect.drawio.svg
  blueprints/01-getting-started/main.tf
Labels: chore

#134 [Makefile] Adding pre-commit target
  Makefile
Labels: chore

#135 [CI] Moving AWS_REGION "us-west-1"
  .cloudbees/workflows/bp-tf-ci.yaml
Labels: chore

#137 [Casc] Setting branch to main
  blueprints/02-at-scale/casc/oc/items/items-root.yaml
  blueprints/02-at-scale/casc/oc/variables/variables.yaml
  blueprints/02-at-scale/k8s/cbci-values.yml
Labels: chore

#139 Minor copy edits to recently revised docs.
  .cloudbees/workflows/bp-tf-ci.yaml
  CONTRIBUTING.md
  blueprints/01-getting-started/README.md
  blueprints/02-at-scale/README.md
  blueprints/02-at-scale/k8s/bottlerocket-update-operator.yml
  blueprints/02-at-scale/main.tf
  blueprints/02-at-scale/outputs.tf
Labels: documentation, Do not merge

#140 [Blueprint 02-At scale] Migration to helm-openldap/openldap-stack-ha: Avoid hardcoded secrets in ldif file
  README.md
  blueprints/02-at-scale/README.md
  blueprints/02-at-scale/casc/oc/items/items-admin-jobs-folder.yaml
  blueprints/02-at-scale/casc/oc/items/items-root.yaml
  blueprints/02-at-scale/casc/oc/jcasc/main.yaml
  blueprints/02-at-scale/casc/oc/jcasc/security.yaml
  blueprints/02-at-scale/casc/oc/variables/variables.yaml
  blueprints/02-at-scale/k8s/cbci-values.yml
  blueprints/02-at-scale/k8s/openldap-stack-values.yml
  blueprints/02-at-scale/k8s/osixia-openldap/.helmignore
  blueprints/02-at-scale/k8s/osixia-openldap/Chart.yaml
  blueprints/02-at-scale/k8s/osixia-openldap/templates/ldap-deployment.yaml
  blueprints/02-at-scale/k8s/osixia-openldap/templates/ldap-service.yaml
  blueprints/02-at-scale/k8s/osixia-openldap/values.yaml
  blueprints/02-at-scale/k8s/secrets-values.yml.example
  blueprints/02-at-scale/main.tf
  blueprints/02-at-scale/outputs.tf
  main.tf
  variables.tf
Labels: enhancement, security

#142 [Blueprint alls]: Replacing Example Domain by Acme Domain for consistency
  blueprints/01-getting-started/.auto.tfvars.example
  blueprints/02-at-scale/.auto.tfvars.example
Labels: documentation

#145 [Blueprints, 02-at-scale]: Use Secrets to pass terraform variables to Casc (part II)
  blueprints/02-at-scale/README.md
  blueprints/02-at-scale/casc/oc/items/items-root.yaml
  blueprints/02-at-scale/casc/oc/variables/variables.yaml
  blueprints/02-at-scale/k8s/cbci-values.yml
Labels: enhancement

#146 [CI] Release drafter update
  .github/release-drafter.yml
Labels: chore

#148 [CI] Replace set-casc-branch by set-casc-location
  Makefile
  blueprints/02-at-scale/k8s/cbci-values.yml
  blueprints/helpers.sh
Labels: chore

#149 [Doc] Contribution guide update
  .cloudbees/workflows/bp-tf-ci.yaml
  CONTRIBUTING.md
Labels: documentation

#150 [Release 3.17821.0] COE Review
  .cloudbees/workflows/bp-tf-ci.yaml
  .cloudbees/workflows/ldap-dh.yaml
  .cloudbees/workflows/ldap-gh.yaml
  .docker/ldap/data.ldif
  .docker/ldap/openldap.Dockerfile
  .github/release-drafter.yml
  .github/workflows/terraform.yml
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  blueprints/.k8s.env
  blueprints/01-getting-started/.auto.tfvars.example
  blueprints/01-getting-started/main.tf
  blueprints/02-at-scale/.auto.tfvars.example
  blueprints/02-at-scale/README.md
  blueprints/02-at-scale/casc/mc/parent/jcasc/main.yaml
  blueprints/02-at-scale/casc/mc/parent/variables/variables.yaml
  blueprints/02-at-scale/casc/oc/items/items-admin-jobs-folder.yaml
  blueprints/02-at-scale/casc/oc/items/items-root.yaml
  blueprints/02-at-scale/casc/oc/jcasc/main.yaml
  blueprints/02-at-scale/casc/oc/jcasc/security.yaml
  blueprints/02-at-scale/casc/oc/variables/variables.yaml
  blueprints/02-at-scale/k8s/cbci-values.yml
  blueprints/02-at-scale/k8s/openldap-stack-values.yml
  blueprints/02-at-scale/k8s/osixia-openldap/.helmignore
  blueprints/02-at-scale/k8s/osixia-openldap/Chart.yaml
  blueprints/02-at-scale/k8s/osixia-openldap/templates/ldap-deployment.yaml
  blueprints/02-at-scale/k8s/osixia-openldap/templates/ldap-service.yaml
  blueprints/02-at-scale/k8s/osixia-openldap/values.yaml
  blueprints/02-at-scale/k8s/secrets-values.yml
  blueprints/02-at-scale/k8s/secrets-values.yml.example
  blueprints/02-at-scale/main.tf
  blueprints/02-at-scale/outputs.tf
  blueprints/02-at-scale/providers.tf
  blueprints/02-at-scale/variables.tf
  blueprints/helpers.sh
  main.tf
  variables.tf
Labels: documentation
